site_name: Stripe Payment Processor (https://stripe.com)
repo_url: https://lab.civicrm.org/extensions/stripe
theme:
  name: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

nav:
- About: index.md
- Examples / Screenshots: examples.md
- Installation: install.md
- Setup: setup.md
- Webhooks (Notifications): webhook.md
- FAQs: faqs.md
- Integrations: integration.md
- Recurring Contributions (Subscriptions): recur.md
- Advanced:
  - API: api.md
  - Events and custom form integrations: events.md
  - Hooks: hooks.md
  - Testing: testing.md
- Release Notes: releasenotes.md
- Roadmap: roadmap.md
