site_name: MJWShared (Extension containing shared code used by MJW extensions)
repo_url: https://lab.civicrm.org/extensions/mjwshared
theme:
  name: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

nav:
- Overview: index.md
- API: api.md
- Refund UI: refunds.md
- Release Notes: releasenotes.md
